### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by Zainde** [Zainde/Yeet#2]

**Comment by trin4988** [comment]
![blog](https://user-images.githubusercontent.com/42169197/44080900-a72d3618-9fad-11e8-9c45-d827d1126a69.jpg)
![gaveaesker](https://user-images.githubusercontent.com/42169197/44080902-a74fa41e-9fad-11e8-89c1-d08462653fea.jpg)
![pre04](https://user-images.githubusercontent.com/42169197/44080903-a76991f8-9fad-11e8-9f1b-19ecbc7f8f8d.jpg)
![tearoom](https://user-images.githubusercontent.com/42169197/44080904-a782d564-9fad-11e8-817f-d0de570d9a51.jpg)
